// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/prateeknayak/pg-kube-crd-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// MyFirstCRDs returns a MyFirstCRDInformer.
	MyFirstCRDs() MyFirstCRDInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// MyFirstCRDs returns a MyFirstCRDInformer.
func (v *version) MyFirstCRDs() MyFirstCRDInformer {
	return &myFirstCRDInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
