// This file was automatically generated by informer-gen

package v1alpha1

import (
	mycontroller_v1alpha1 "github.com/prateeknayak/pg-kube-crd-controller/pkg/apis/mycontroller/v1alpha1"
	versioned "github.com/prateeknayak/pg-kube-crd-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/prateeknayak/pg-kube-crd-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/prateeknayak/pg-kube-crd-controller/pkg/client/listers/mycontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MyFirstCRDInformer provides access to a shared informer and lister for
// MyFirstCRDs.
type MyFirstCRDInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MyFirstCRDLister
}

type myFirstCRDInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMyFirstCRDInformer constructs a new informer for MyFirstCRD type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMyFirstCRDInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMyFirstCRDInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMyFirstCRDInformer constructs a new informer for MyFirstCRD type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMyFirstCRDInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycontrollerV1alpha1().MyFirstCRDs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MycontrollerV1alpha1().MyFirstCRDs(namespace).Watch(options)
			},
		},
		&mycontroller_v1alpha1.MyFirstCRD{},
		resyncPeriod,
		indexers,
	)
}

func (f *myFirstCRDInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMyFirstCRDInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *myFirstCRDInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mycontroller_v1alpha1.MyFirstCRD{}, f.defaultInformer)
}

func (f *myFirstCRDInformer) Lister() v1alpha1.MyFirstCRDLister {
	return v1alpha1.NewMyFirstCRDLister(f.Informer().GetIndexer())
}
