// This file was automatically generated by lister-gen

package v1alpha1

// MyFirstCRDListerExpansion allows custom methods to be added to
// MyFirstCRDLister.
type MyFirstCRDListerExpansion interface{}

// MyFirstCRDNamespaceListerExpansion allows custom methods to be added to
// MyFirstCRDNamespaceLister.
type MyFirstCRDNamespaceListerExpansion interface{}
